---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    version: "2.0.0"
    name: elastic
  - src: git@github.com:Pitonixx/kibana-role.git
    version: "1.0.1"
    name: kibana-role
  - src: git@github.com:Pitonixx/filebeat-role.git
    version: "1.0.1"
    name: filebeat-role
